<?php
// server/seed.php
// Dev-only helper: fills an empty `leaf` database with fake users and plants,
// then posts every plant as an OPEN sit. Seeded users never claim a sit —
// sitter_id, sitter_note, and claimed_at stay null on every row, so the
// pool is just a wide spread of browsable listings across every region.
//
// Care notes are picked from the hardcoded list below, not generated by
// ai-care.php — seeding should never spend AI API credits.
//
// Meant to run once against an empty database. Re-running it will collide
// with the UNIQUE constraints on users.username / users.email.

include_once("connection.php");

$demo_password_hash = password_hash("leafdemo123", PASSWORD_DEFAULT);

$fake_users = [
    ["mira_k",   "mira.k@example.com",   "Beirut"],
    ["tarek_h",  "tarek.h@example.com",  "Metn"],
    ["layla_s",  "layla.s@example.com",  "Keserwan"],
    ["omar_j",   "omar.j@example.com",   "Baabda"],
    ["dina_r",   "dina.r@example.com",   "Aley"],
    ["khalil_m", "khalil.m@example.com", "Chouf"],
    ["nour_a",   "nour.a@example.com",   "Jbeil"],
    ["sami_f",   "sami.f@example.com",   "Batroun"],
    ["rana_z",   "rana.z@example.com",   "Tripoli"],
    ["fadi_c",   "fadi.c@example.com",   "Zahle"],
    ["yara_b",   "yara.b@example.com",   "Saida"],
    ["hadi_n",   "hadi.n@example.com",   "Tyre"],
];

$user_ids = [];
$sql_user = "INSERT INTO users (username, email, region, password_hash) VALUES (?, ?, ?, ?)";
$stmt_user = $mysql->prepare($sql_user);
foreach ($fake_users as $user) {
    list($username, $email, $region) = $user;
    $stmt_user->bind_param("ssss", $username, $email, $region, $demo_password_hash);
    $stmt_user->execute();
    $user_ids[] = $stmt_user->insert_id;
}
$stmt_user->close();

// Hardcoded, generic placeholder care notes — never call generate_care_notes() here.
$placeholder_care_notes = [
    "Water when the top inch of soil feels dry. Keep near indirect light.",
    "Prefers bright, indirect light and a light watering once the soil surface dries out.",
    "Tolerates some neglect. Water sparingly and keep out of direct afternoon sun.",
    "Needs consistent moisture but not standing water. Keep away from cold drafts.",
    "Likes humidity. Mist occasionally and water once the topsoil is dry to the touch.",
    "Low maintenance. Water every one to two weeks and keep in moderate light.",
];

$fake_plants = [
    ["Fig",      "Ficus lyrata"],
    ["Mint",     "Mentha spicata"],
    ["Sable",    "Sansevieria trifasciata"],
    ["Pepper",   "Piper nigrum"],
    ["Basil",    "Ocimum basilicum"],
    ["Ivy",      "Hedera helix"],
    ["Jade",     "Crassula ovata"],
    ["Fern",     "Nephrolepis exaltata"],
    ["Aloe",     "Aloe vera"],
    ["Pothos",   "Epipremnum aureum"],
    ["Rosemary", "Salvia rosmarinus"],
    ["Lavender", "Lavandula angustifolia"],
    ["Cactus",   "Echinocactus grusonii"],
    ["Palm",     "Chamaedorea elegans"],
];

$plant_ids = [];
$sql_plant = "INSERT INTO plants (owner_id, name, species, care_notes) VALUES (?, ?, ?, ?)";
$stmt_plant = $mysql->prepare($sql_plant);
foreach ($fake_plants as $i => $plant) {
    list($name, $species) = $plant;
    $owner_id = $user_ids[$i % count($user_ids)];
    $care_notes = $placeholder_care_notes[$i % count($placeholder_care_notes)];
    $stmt_plant->bind_param("isss", $owner_id, $name, $species, $care_notes);
    $stmt_plant->execute();
    $plant_ids[] = $stmt_plant->insert_id;
}
$stmt_plant->close();

// Every plant gets one OPEN sit, nothing claimed. sitter_id / sitter_note /
// claimed_at stay null so seeded users never show up as having sat for
// anything — this is just listing inventory to browse.
$today = new DateTime();

$sql_sit = "INSERT INTO sits (plant_id, sitter_id, start_date, end_date, status, sitter_note, claimed_at) VALUES (?, ?, ?, ?, 'open', ?, ?)";
$stmt_sit = $mysql->prepare($sql_sit);

$sitter_id = null;
$sitter_note = null;
$claimed_at = null;

foreach ($plant_ids as $i => $plant_id) {
    $start_date = (clone $today)->modify("+" . (2 + $i) . " days")->format("Y-m-d");
    $end_date = (clone $today)->modify("+" . (7 + $i) . " days")->format("Y-m-d");

    $stmt_sit->bind_param("iissss", $plant_id, $sitter_id, $start_date, $end_date, $sitter_note, $claimed_at);
    $stmt_sit->execute();
}
$stmt_sit->close();

echo "Seeded " . count($user_ids) . " users, " . count($plant_ids) . " plants, " . count($plant_ids) . " open sits.\n";
?>