<?php
// server/seed.php
// Dev-only helper: fills an empty `leaf` database with fake users, plants,
// and sits so the app has something to look at while developing.
//
// Care notes are picked from the hardcoded list below, not generated by
// ai-care.php — seeding should never spend AI API credits.
//
// Meant to run once against an empty database. Re-running it will collide
// with the UNIQUE constraints on users.username / users.email.

include_once("connection.php");

$demo_password_hash = password_hash("leafdemo123", PASSWORD_DEFAULT);

$fake_users = [
    ["mira_k",   "mira.k@example.com",   "Beirut"],
    ["tarek_h",  "tarek.h@example.com",  "Metn"],
    ["layla_s",  "layla.s@example.com",  "Keserwan"],
    ["omar_j",   "omar.j@example.com",   "Baabda"],
    ["dina_r",   "dina.r@example.com",   "Aley"],
    ["khalil_m", "khalil.m@example.com", "Chouf"],
];

$user_ids = [];
$sql_user = "INSERT INTO users (username, email, region, password_hash) VALUES (?, ?, ?, ?)";
$stmt_user = $mysql->prepare($sql_user);
foreach ($fake_users as $user) {
    list($username, $email, $region) = $user;
    $stmt_user->bind_param("ssss", $username, $email, $region, $demo_password_hash);
    $stmt_user->execute();
    $user_ids[] = $stmt_user->insert_id;
}
$stmt_user->close();

// Hardcoded, generic placeholder care notes — never call generate_care_notes() here.
$placeholder_care_notes = [
    "Water when the top inch of soil feels dry. Keep near indirect light.",
    "Prefers bright, indirect light and a light watering once the soil surface dries out.",
    "Tolerates some neglect. Water sparingly and keep out of direct afternoon sun.",
    "Needs consistent moisture but not standing water. Keep away from cold drafts.",
    "Likes humidity. Mist occasionally and water once the topsoil is dry to the touch.",
    "Low maintenance. Water every one to two weeks and keep in moderate light.",
];

$fake_plants = [
    ["Fig",    "Ficus lyrata"],
    ["Mint",   "Mentha spicata"],
    ["Sable",  "Sansevieria trifasciata"],
    ["Pepper", "Piper nigrum"],
    ["Basil",  "Ocimum basilicum"],
    ["Ivy",    "Hedera helix"],
    ["Jade",   "Crassula ovata"],
    ["Fern",   "Nephrolepis exaltata"],
    ["Aloe",   "Aloe vera"],
];

$plant_ids = [];
$plant_owner_ids = [];
$sql_plant = "INSERT INTO plants (owner_id, name, species, care_notes) VALUES (?, ?, ?, ?)";
$stmt_plant = $mysql->prepare($sql_plant);
foreach ($fake_plants as $i => $plant) {
    list($name, $species) = $plant;
    $owner_id = $user_ids[$i % count($user_ids)];
    $care_notes = $placeholder_care_notes[$i % count($placeholder_care_notes)];
    $stmt_plant->bind_param("isss", $owner_id, $name, $species, $care_notes);
    $stmt_plant->execute();
    $plant_ids[] = $stmt_plant->insert_id;
    $plant_owner_ids[] = $owner_id;
}
$stmt_plant->close();

$placeholder_sitter_notes = [
    "Watered on schedule and rotated the pot for even light. No issues.",
    "Soil was drier than expected on the first visit, watered a little extra. Otherwise fine.",
    "All good. A couple of yellow leaves were trimmed off.",
    "Kept to the care notes. Plant looked healthy at drop-off.",
];

$statuses = ["open", "claimed", "completed"];
$today = new DateTime();

$sql_sit = "INSERT INTO sits (plant_id, sitter_id, start_date, end_date, status, sitter_note, claimed_at) VALUES (?, ?, ?, ?, ?, ?, ?)";
$stmt_sit = $mysql->prepare($sql_sit);

foreach ($plant_ids as $i => $plant_id) {
    $status = $statuses[$i % count($statuses)];
    $owner_id = $plant_owner_ids[$i];

    // pick a sitter who is not this plant's owner, rotating through users for variety
    $sit_sitter_id = $user_ids[($i + 1) % count($user_ids)];
    if ($sit_sitter_id == $owner_id) {
        $sit_sitter_id = $user_ids[($i + 2) % count($user_ids)];
    }

    if ($status == "open") {
        $start_date = (clone $today)->modify("+" . (3 + $i) . " days")->format("Y-m-d");
        $end_date = (clone $today)->modify("+" . (8 + $i) . " days")->format("Y-m-d");
        $sitter_id = null;
        $sitter_note = null;
        $claimed_at = null;
    } elseif ($status == "claimed") {
        $start_date = (clone $today)->modify("-2 days")->format("Y-m-d");
        $end_date = (clone $today)->modify("+3 days")->format("Y-m-d");
        $sitter_id = $sit_sitter_id;
        $sitter_note = null;
        $claimed_at = (clone $today)->modify("-2 days")->format("Y-m-d H:i:s");
    } else {
        $start_date = (clone $today)->modify("-" . (10 + $i) . " days")->format("Y-m-d");
        $end_date = (clone $today)->modify("-" . (5 + $i) . " days")->format("Y-m-d");
        $sitter_id = $sit_sitter_id;
        $sitter_note = $placeholder_sitter_notes[$i % count($placeholder_sitter_notes)];
        $claimed_at = (clone $today)->modify("-" . (10 + $i) . " days")->format("Y-m-d H:i:s");
    }

    $stmt_sit->bind_param("iisssss", $plant_id, $sitter_id, $start_date, $end_date, $status, $sitter_note, $claimed_at);
    $stmt_sit->execute();
}
$stmt_sit->close();

echo "Seeded " . count($user_ids) . " users, " . count($plant_ids) . " plants, " . count($plant_ids) . " sits.\n";
?>
